name: build-linux

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
        
    - name: Updating Dependencies
      run: |
        sudo apt update
        sudo apt upgrade
        sudo apt-get update
        sudo apt-get upgrade

    - name: Installing Dependencies
      run: sudo apt install xorg-dev

    - name: Generate Project Files
      run: cmake -S . -B build

    - name: Build Solution
      run: |
        cd build
        make
