name: build-linux

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Setup Compiler
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10

    - name: Installing Dependencies
      run: sudo apt install xorg-dev

    - name: Generate Project Files
      run: cmake -S . -B build
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Build Solution
      run: |
        cd build
        make
