name: build-linux

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Installing Dependencies
      run: sudo apt install xorg-dev

    - name: Generate Project Files
      run: sh ./Scripts/Linux-GenProjects.sh

    - name: Build Solution
      run: make
