name: build-linux

on: [ push, pull_request ]

jobs:
  build-linux:
    runs-on: ubuntu-18.04
    defaults:
      run:
        shell: bash
    steps:
    - name: Caching Submodules
      uses: actions/cache@v2
      id: cache-submodules
      env:
        cache-name: cache-submodules
      with:
        key: ${{ runner.os }}-build-${{ env.cache-name }}
        path: vendor

    - name: Download Submodules
      if: steps.cache-submodules.outputs.cache-hit != 'true'
      uses: actions/checkout@v2
      with:
        submodules: recursive

    - name: Installing Dependencies
      run: |
        sudo apt update
        sudo apt install gcc-10 g++-10
        sudo apt install xorg-dev

    - name: Generate Project Files
      run: cmake -S . -B build
      env:
        CC: gcc-10
        CXX: g++-10

    - name: Build Solution
      run: |
        cd build
        make
